DBType: sqlserver
DriverName: com.microsoft.sqlserver.jdbc.SQLServerDriver
DatabaseName: JB4DC_DEV_MOCK_V01
Url: jdbc:sqlserver://127.0.0.1:1433; DatabaseName=JB4DC_DEV_MOCK_V01
User: sa
Password: sql